path.n: NAMESPACE
path.d: DESCRIPTION
dir.r: R
dir.v: vignettes
dir.t: tests
extra.suggests:
   - tibble
   - tidygeocoder
pkg_ignore:
  - tidyterra
  - htmltools
  - crosstalk
  - leaflet
  - mapSpain
  - maptiles
  - reactable
document: no
normalize: yes
inside_rmd: ~
must.exist: yes
check_if_suggests_is_installed: yes
