---
title: "Example: arcgeocoder and leaflet maps"
subtitle: "Combine arcgeocoder and leaflet maps"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  dpi = 300,
  tidy = "styler",
  dev = "ragg_png",
  out.width = "100%"
)
```

## Example

The following example shows how it is possible to create a nice [leaflet
map](https://rstudio.github.io/leaflet/) with data retrieved with
**arcgeocoder**:

```{r example}
# Coffee Shops and Bakeries around the Eiffel Tower

library(arcgeocoder)
library(leaflet)
library(dplyr)

# Step 1: Eiffel Tower

eiffel_tower <- arc_geo_multi("Eiffel Tower",
  city = "Paris", countrycode = "FR",
  category = "POI"
)

# Base url for icons
icon_url <- paste0(
  "https://raw.githubusercontent.com/dieghernan/arcgeocoder/",
  "main/vignettes/articles/"
)
eiffel_icon <- makeIcon(
  iconUrl = paste0(icon_url, "eiffel-tower.png"),
  iconWidth = 50, iconHeight = 50,
  iconAnchorX = 25, iconAnchorY = 25
)

# Leaflet map
lm <- leaflet(
  elementId = "EiffelTower", width = "100%", height = "60vh",
  options = leafletOptions(minZoom = 12)
) %>%
  addProviderTiles(
    provider = "CartoDB.Positron",
    group = "CartoDB.Positron"
  ) %>%
  addTiles(group = "OSM") %>%
  addMarkers(data = eiffel_tower, ~lon, ~lat, icon = eiffel_icon)


# Step 2: Coffee Shops nearby
cf <- arc_geo_categories("Coffee Shop",
  x = eiffel_tower$lon, y = eiffel_tower$lat,
  limit = 50, full_results = TRUE
)

# Label for PopUp
cf$labelpop <- paste0("<strong>", cf$PlaceName, "</strong><br>", cf$StAddr)

coffee_icon <- makeIcon(
  iconUrl = paste0(icon_url, "coffee-cup.png"),
  iconWidth = 20, iconHeight = 20,
  iconAnchorX = 10, iconAnchorY = 10
)

lm <- lm %>%
  addMarkers(
    data = cf, ~lon, ~lat, popup = ~labelpop, icon = coffee_icon,
    group = "Coffee Shops"
  )

# Step 3: Bakeries nearby
bk <- arc_geo_categories("Bakery",
  x = eiffel_tower$lon, y = eiffel_tower$lat,
  limit = 50, full_results = TRUE
)

# Label for PopUp
bk$labelpop <- paste0("<strong>", bk$PlaceName, "</strong><br>", bk$StAddr)

bk_icon <- makeIcon(
  iconUrl = paste0(icon_url, "croissant.png"),
  iconWidth = 20, iconHeight = 20,
  iconAnchorX = 10, iconAnchorY = 10
)

lm <- lm %>%
  addMarkers(
    data = bk, ~lon, ~lat, popup = ~labelpop, icon = bk_icon,
    group = "Bakeries"
  )

# Add layer control

lm <- lm %>%
  addLayersControl(
    baseGroups = c("CartoDB.Positron", "OSM"),
    overlayGroups = c("Coffee Shops", "Bakeries"),
    position = "topleft",
    options = layersControlOptions(collapsed = FALSE)
  )

lm
```

## Attributions

-   [Eiffel tower icons created by Freepik -
    Flaticon](https://www.flaticon.com/free-icons/eiffel-tower "eiffel tower icons")
-   [Mug icons created by Freepik -
    Flaticon](https://www.flaticon.com/free-icons/mug "mug icons")
-   [Croissant icons created by Freepik -
    Flaticon](https://www.flaticon.com/free-icons/croissant "croissant icons")
    
## Session info

<details>
  <summary>Details</summary>
  
```{r session, echo=FALSE}
if (!require("sessioninfo")) {
  install.packages("sessioninfo")
}
sessioninfo::session_info()
```
</details>

